version: '3.7'

volumes:
  data:

networks:
  nets:
    driver: bridge

services:
  webserver:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - nets
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - language
      - mariadb
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 8080
      
  language:
    image: php:8.2-fpm-alpine
    networks:
      - nets
    volumes:
      - ./www/:/usr/share/nginx/html
    environment:
      PHP_FPM_LISTEN: "9000"

  mariadb:
    image: mariadb:10.6.8
    networks:
      - nets
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypass"
      MYSQL_DATABASE: "mydb"
    command: --backup --backup-name=db-backups

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    ports:
      - "8181:80"
    networks:
      - nets
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
