version: '3.7'

volumes:
  data:

networks:
  nets:
    driver: bridge

services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: always
    ports:
      - "8080:80"
    networks:
      - nets
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./entrypoint.sh:/entrypoint.sh
    depends_on:
      - language
      - mariadb
    environment:
      PHP_FPM_HOST: "language"
      PHP_FPM_PORT: "9000"
    entrypoint: ["sh", "/entrypoint.sh"]
      
  language:
    image: php:8.2-fpm-alpine
    container_name: language
    restart: always
    networks:
      - nets
    volumes:
      - ./www/:/usr/share/nginx/html
    environment:
      PHP_FPM_LISTEN: "9000"

  mariadb:
    image: mariadb:10.6.8
    container_name: mariadb
    restart: always
    networks:
      - nets
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypass"
      MYSQL_DATABASE: "mydb"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8181:80"
    networks:
      - nets
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
