version: '3.7'

volumes:
  mariadb-data:
  mariadb-data-backups:
  src:

networks:
  nets:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - nets
    volumes:
      - src:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8.2-fpm-alpine
    networks:
      - nets
    volumes:
      - src:/usr/share/nginx/html
      - ./www:/usr/share/nginx/html

  mariadb:
    image: mariadb:10.6.8
    networks:
      - nets
    volumes:
      - mariadb-data:/var/lib/mysql
      - mariadb-data-backups:/var/lib/mysql-backups
      - ./database-backups://var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypass"
      MYSQL_DATABASE: "mydb"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    ports:
      - "8181:80"
    networks:
      - nets
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
