version: '3.8'

services:
  mariadb:
    image: docker.io/library/mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - lamp-pod

  php-fpm:
    image: docker.io/library/php:8.2-fpm-alpine
    container_name: php-fpm
    volumes:
      - app-data:/var/www/html
    networks:
      - lamp-pod

  nginx:
    image: docker.io/library/nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - app-data:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    networks:
      - lamp-pod

  phpmyadmin:
    image: docker.io/library/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    networks:
      - lamp-pod

volumes:
  app-data:
  db-data:

networks:
  lamp-pod: